// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uumijaamtpwnbzhtgyvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1bWlqYWFtdHB3bmJ6aHRneXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDQwNDQsImV4cCI6MjA1OTg4MDA0NH0.IfEj58GjtDqMb96sYs0HVV-inAy3vgwWgN9JIp0T9FA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);